[package]
name = "myprotobuf"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12"
prost-derive = "0.12"
nalgebra = "0.32"
prost-types = "0.12"

[build-dependencies]
prost-build = "0.12"
protoc-bin-vendored = "3.0"